#! /bin/bash
bspc rule -r "*"

pgrep -x sxhkd > /dev/null || sxhkd &

# Monitor setup
if xrandr --listactivemonitors | grep "Monitors: 1" && xrandr --listactivemonitors | grep "LVDS1"
then
	bspc monitor LVDS1 -d I II III IV V VI VII VIII IX X
	killall polybar ; polybar primary &
fi

if xrandr --listactivemonitors | grep "Monitors: 1" && xrandr --listactivemonitors | grep "HDMI1"
then
	bspc monitor HDMI1 -d I II III IV V VI VII VIII IX X
	killall polybar ; polybar hdmi &
fi

if xrandr --listactivemonitors | grep "Monitors: 2" && xrandr --listactivemonitors | grep "HDMI1"
then
	bspc monitor LVDS1 -d I II III IV V
	bspc monitor HDMI1 -d VI VII VIII IX X
	killall polybar ; polybar primary &
fi

bspc config border_width         2
bspc config window_gap          6

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config single_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier super
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config focused_border_color "#98971a"
bspc config presel_feedback_color "#d79921"
bspc config urgent_border_color "#cc241d"

bspc rule -a MEGAsync state=floating

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

xfsettingsd &# To set themes etc.
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
start-pulseaudio-x11 &
killall pa-applet ; pa-applet &
killall nm-applet ; nm-applet &
xfce4-power-manager &
dropbox &
megasync &
pamac-tray &
nitrogen --restore; sleep 1; picom -b &
